create table parking_lot (id integer generated by default as identity, capacity integer not null check (capacity<=9223372036854775807 AND capacity>=0), name varchar(255), position varchar(255), primary key (id));
alter table parking_lot drop constraint if exists UK_cgtj8ovhkxgh6pqsn8rbj5b4g;
alter table parking_lot add constraint UK_cgtj8ovhkxgh6pqsn8rbj5b4g unique (name);